kind: Template
apiVersion: template.openshift.io/v1
parameters:
- name: ID
  required: true
- name: IMAGE
  #value: quay.io/amcdermo/ocpbugs-173-server:latest
  value: quay.io/openshift-scale/nginx
objects:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    labels:
      app: http-perf-${ID}
    name: http-perf-${ID}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: http-perf-${ID}
    template:
      metadata:
        labels:
          app: http-perf-${ID}
      spec:
        containers:
        - name: server
          image: ${IMAGE}
          volumeMounts:
          - mountPath: /etc/serving-cert
            name: cert
          readinessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
        volumes:
        - name: cert
          secret:
            secretName: http-perf-${ID}-serving-cert
