kind: Template
apiVersion: template.openshift.io/v1
parameters:
- name: ID
  required: true
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: http-perf-${ID}
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: http-perf-${ID}-serving-cert
  spec:
    selector:
      app: http-perf-${ID}
    ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
