apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ocpbugs13966-passthrough
  labels:
    app: ocpbugs13966-test
spec:
  tls:
    termination: passthrough
  to:
    kind: Service
    name: ocpbugs13966-test
    weight: 100
  wildcardPolicy: None
