apiVersion: v1
kind: Service
metadata:
  name: ocpbugs13966-test
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: serving-cert-ocpbugs13966-test
spec:
  selector:
    app: ocpbugs13966-test
  ports:
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
