apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ocpbugs14914-passthrough
  labels:
    app: ocpbugs14914-test
spec:
  port:
    targetPort: 8443
  tls:
    termination: passthrough
  to:
    kind: Service
    name: ocpbugs14914-test
    weight: 100
  wildcardPolicy: None
