apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: yages
spec:
  to:
    kind: Service
    name: yages
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    key: |-
    certificate: |-
  selector:
    app: yages
