apiVersion: v1
kind: Service
metadata:
  name: destca
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: serving-cert-destca
spec:
  selector:
    app: destca
  ports:
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
