apiVersion: apps/v1
kind: Deployment
metadata:
  name: destca
spec:
  selector:
    matchLabels:
      app: destca
  template:
    metadata:
      labels:
        app: destca
    spec:
      containers:
      - name: server
        image: registry.int.frobware.com/destca/html-server
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        volumeMounts:
        - mountPath: /etc/serving-cert
          name: cert
        env:
        - name: GODEBUG
          value: http2debug=2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 30
          successThreshold: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 30
          successThreshold: 1
      volumes:
      - name: cert
        secret:
          secretName: serving-cert-destca
