apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: TLS_CACRT
- name: TLS_CRT
- name: TLS_KEY
- name: DEST_CACRT
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: payroll
    labels:
      app: destca
  spec:
    port:
      targetPort: 8443
    tls:
      termination: reencrypt
      insecureEdgeTerminationPolicy: Redirect
      key: |-
        ${TLS_KEY}
      certificate: |-
        ${TLS_CRT}
      caCertificate: |-
        ${TLS_CACRT}
    to:
      kind: Service
      name: destca
      weight: 100
    wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: catpictures
    labels:
      app: destca
  spec:
    port:
      targetPort: 8443
    tls:
      termination: reencrypt
      insecureEdgeTerminationPolicy: Redirect
      key: |-
        ${TLS_KEY}
      certificate: |-
        ${TLS_CRT}
      caCertificate: |-
        ${TLS_CACRT}
    to:
      kind: Service
      name: destca
      weight: 100
    wildcardPolicy: None
