apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocpbugs40850-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocpbugs40850-test
  template:
    metadata:
      labels:
        app: ocpbugs40850-test
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: ocpbugs40850-test
        image: quay.io/amcdermo/ocpbugs40850-server:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: HEALTH_PORT
          value: "1050"
        - name: SINGLE_TE_PORT
          value: "1030"
        - name: DUPLICATE_TE_PORT
          value: "1040"
        ports:
        - containerPort: 1030
          protocol: TCP
          name: "single-te"
        - containerPort: 1040
          protocol: TCP
          name: "duplicate-te"
        - containerPort: 1050
          protocol: TCP
          name: "health-port"
        readinessProbe:
          httpGet:
            path: /
            port: 1050
          initialDelaySeconds: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 1050
          initialDelaySeconds: 1
          periodSeconds: 10
