apiVersion: v1
kind: List
items:
- apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: perf
    namespace: openshift-ingress-operator
  spec:
    replicas: 1
    domain: perf.ocp411.int.frobware.com
    endpointPublishingStrategy:
      type: LoadBalancerService
    nodePlacement:
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/worker: ""
    namespaceSelector:
      matchLabels:
        environment: perf
    routeSelector:
      matchLabels:
        type: perf
