---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: perf-server
parameters:
- name: IMAGE
  value: quay.io/amcdermo/perf-server:latest
  required: true
objects:
- kind: Service
  apiVersion: v1  
  metadata:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: ocpbugs-173-cert
    labels:
      app: perf-server
    name: perf-server
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    selector:
      app: perf-server
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    labels:
      app: perf-server
    name: perf-server
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: perf-server
    template:
      metadata:
        labels:
          app: perf-server
      spec:
        containers:
        - name: perf-server
          image: ${IMAGE}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
          - mountPath: /etc/serving-cert
            name: cert
          readinessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        volumes:
        - name: cert
          secret:
            secretName: ocpbugs-173-cert
