apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-server
spec:
  selector:
    matchLabels:
      app: html-server
  template:
    metadata:
      labels:
        app: html-server
    spec:
      containers:
      - name: html-server
        image: registry.int.frobware.com/destca/html-server
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 8443
          protocol: TCP
          name: "https"
        volumeMounts:
        - mountPath: /etc/serving-cert
          name: cert
      volumes:
      - name: cert
        secret:
          secretName: serving-cert-html-server
