apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: TLS_CACRT
- name: TLS_CRT
- name: TLS_KEY
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: html-server-insecure
    labels:
      app: html-server
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: html-server
      weight: 100
    wildcardPolicy: None
