apiVersion: v1
kind: Service
metadata:
  name: html-server
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: serving-cert-html-server
spec:
  selector:
    app: html-server
  ports:
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
