apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocpbugs16707-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocpbugs16707-deployment
  template:
    metadata:
      labels:
        app: ocpbugs16707-deployment
    spec:
      containers:
      - name: server
        image: registry.int.frobware.com/ocpbugs16707/server
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 8080
          protocol: TCP
          name: "http"
        readinessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 4242
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
        livenessProbe:
          failureThreshold: 1
          tcpSocket:
            port: 4242
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
