apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: browser-test-insecure
  labels:
    app: browser-test
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: browser-test
    weight: 100
  wildcardPolicy: None
