---
- name: install autofs, setup common mountpoints
  become: true
  gather_facts: false
  hosts: all
  tasks:
  - name: Install autofs packages
    yum:
      name: autofs, nfs-utils
      state: present
  - name: Create /etc/auto.u
    copy:
      content: |
        aim -rw,soft,intr 10.19.96.50:/nfs/share
      dest: /etc/auto.u
      force: yes
      group: root
      owner: root
      mode: 0644
  - name: Add to /etc/auto.master
    copy:
      content: |
        /u /etc/auto.u
      dest: /etc/auto.master
      force: yes
      group: root
      owner: root
      mode: 0644
  - name: Enable autofs
    systemd: name=autofs daemon_reload=true enabled=yes
  - name: Restart autofs
    command: systemctl restart autofs
