---
- name: install docker, docker-compose
  gather_facts: true
  hosts: perf_backend

  tasks:
  - name: Install yum utils
    yum:
      name: yum-utils
      state: present

  - name: set host distribution
    set_fact:
      distro: "centos"

  - name: Add signing key
    rpm_key:
      key: "https://download.docker.com/linux/{{ distro }}/gpg"
      state: present

  - name: Add repo
    command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      
  - name: Install Docker
    ansible.builtin.yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
      update_cache: true

  - name: Start Docker
    ansible.builtin.service:
      name: "docker"
      enabled: true
      state: started

  - name: Install docker-compose
    get_url: 
      url: https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64
      dest: /usr/bin/docker-compose
      mode: 0555
