---
- name: mask firewall
  gather_facts: false
  hosts: all
  tasks:
  - name: mask firewall service
    command: systemctl mask --now firewalld
  # - name: start systemd firewall service
  #   systemd:
  #     name: firewalld
  #     state: started


