---
- name: start firewall
  gather_facts: false
  hosts: all
  tasks:
  - name: unmask firewall service
    command: systemctl unmask --now firewalld
  - name: start systemd firewall service
    systemd:
      name: firewalld
      state: started


