---
- name: set resolver configuration
  hosts: all
  tasks:
  - name: Check for hosts in /etc/host.conf
    lineinfile:
      state: absent
      path: "/etc/host.conf"
      regexp: "^order hosts,dns"
    check_mode: true
    changed_when: false
    register: check
  - name: Add hosts to /etc/host.conf
    lineinfile:
      state: present
      path: "/etc/host.conf"
      line: "order hosts,dns"
    when: check.found == 0
