---
- name: add perf_backend user accounts
  hosts: all
  tasks:
  - name: add user aim
    ansible.builtin.user:
      name: aim
      shell: /bin/bash
      groups: wheel
  - name: create hushlogin
    file:
      path: /home/aim/.hushlogin
      state: touch
      mode: 0644
      owner: aim
  - name: Set authorized keys taken from url
    ansible.posix.authorized_key:
      user: aim
      state: present
      key: https://github.com/frobware.keys
  - name: Add user to sudo
    lineinfile:
      path: /etc/sudoers.d/aim
      line: 'aim ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'
- name: add docker group membership for user aim on perf_backend
  hosts: perf_backend
  tasks:
  - name: add docker group to user aim
    ansible.builtin.user:
      name: aim
      groups: docker
      append: yes
