---
- name: add user accounts
  hosts: all
  tasks:
  - name: add user aim
    ansible.builtin.user:
      name: aim
      shell: /bin/bash
      groups: wheel
      state: present
  - name: create hushlogin
    file:
      path: /home/aim/.hushlogin
      state: touch
      mode: 0644
      owner: aim
  - name: Set authorized keys taken from file
    ansible.posix.authorized_key:
      user: aim
      state: present
      key: "{{ lookup('file', '/home/aim/.ssh/id_rsa.pub') }}"
  - name: Add user to sudo
    lineinfile:
      path: /etc/sudoers.d/aim
      line: 'aim ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'
  - name: add bashrc
    copy:
      src: bashrc
      dest: /home/aim/.bashrc
      mode: 0644
      owner: aim
  - name: add git/config
    copy:
      src: git/config
      dest: /home/aim/.gitconfig
      mode: 0644
      owner: aim
  - name: add tmux.conf
    copy:
      src: tmux.conf
      dest: /home/aim/.tmux.conf
      mode: 0644
      owner: aim
  - name: add .ssh/config
    copy:
      src: ssh/config
      dest: /home/aim/.ssh/config
      mode: 0644
      owner: aim
- name: add docker group membership for user aim on perf_backend
  hosts: perf_backend
  tasks:
  - name: add docker group to user aim
    ansible.builtin.user:
      name: aim
      groups: docker
      append: yes
